spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Europe/Berlin
    show-sql: false

app:
  security:
    username: ${APP_SECURITY_USERNAME}
    password: ${APP_SECURITY_PASSWORD}

weather:
  api:
    key: ${WEATHER_API_KEY}
    url: ${WEATHER_API_URL}
  city: ${WEATHER_CITY}
  country: ${WEATHER_COUNTRY}

server:
  port: ${PORT:8080}

ntfy:
  url: https://ntfy.sh
  topic: ${NTFY_TOPIC}
